Make sure bindings.rs is up-to-date (#832)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,6 @@
 name: Build and Test
 
-on: 
+on:
   pull_request:
   push:
     branches:
@@ -12,7 +12,7 @@ env:
 jobs:
   test:
     runs-on: ${{ matrix.os }}
-    strategy: 
+    strategy:
       matrix:
         include:
         - os: windows-latest
@@ -49,4 +49,11 @@ jobs:
 
     - name: fmt
       run: cargo fmt --all -- --check
+      if: matrix.os == 'windows-latest' && matrix.rust == 'stable'
+
+    - name: generate bindings
+      run: |
+        cargo run -p windows_bindings --target ${{ matrix.other }}
+        git diff --exit-code || (echo '::error::Generated bindings are out-of-date. Make sure to update them by running `cargo run -p windows_bindings`'; exit 1)
+      shell: bash
       if: matrix.os == 'windows-latest' && matrix.rust == 'stable'
