test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -38,11 +38,11 @@ jobs:
     - run: rustup update --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
     - run: rustup target add ${{ matrix.other }}
 
-    - name: build linux
+    - name: linux build
       run: cargo build
       if: matrix.os == 'ubuntu-latest'
 
-    - name: test windows
+    - name: windows build
       run: cargo test --all --target ${{ matrix.other }}
       if: matrix.os == 'windows-latest'
 
@@ -52,29 +52,32 @@ jobs:
       run: cargo doc --no-deps --workspace
       if: matrix.os == 'windows-latest' && matrix.rust == 'stable'
 
-    - name: generate bindings
-      run: |
-        cargo run -p windows_bindings --target ${{ matrix.other }}
-        git diff --exit-code || (echo '::error::Generated bindings are out-of-date. Make sure to update them by running `cargo run -p windows_bindings`'; exit 1)
-      shell: bash
-      if: matrix.os == 'windows-latest' && matrix.rust == 'stable'
-
-  windows_fmt:
-    runs-on: windows-latest
-    name: Check `build!` macro formatting
-    steps:
-    - uses: actions/checkout@v2
-    - name: Run `windows_fmt`
-      run: cargo r -p windows_fmt
-    - name: Diff formatting result
-      shell: bash
-      run: git diff --exit-code || (echo '::error::Some `build!` macros were improperly formatted. Please run `cargo run -p windows_fmt` and push again'; exit 1)
-
   cargo_fmt:
     runs-on: windows-latest
     name: Check cargo formatting
     steps:
     - uses: actions/checkout@v2
-    - name: Run `cargo fmt`
+    - name: Run cargo fmt
       run: cargo fmt --all -- --check
 
+  windows_fmt:
+    runs-on: windows-latest
+    name: Check build macro formatting
+    steps:
+    - uses: actions/checkout@v2
+    - name: Run windows_fmt
+      run: cargo r -p windows_fmt
+    - name: Diff formatting result
+      shell: bash
+      run: git diff --exit-code || (echo '::error::Some `build!` macros were improperly formatted. Please run `cargo run -p windows_fmt` and push again'; exit 1)
+
+  windows_bindings:
+    runs-on: windows-latest
+    name: Check bindings
+    steps:
+    - uses: actions/checkout@v2
+    - name: Run windows_bindings
+      run: |
+        cargo run -p windows_bindings --target ${{ matrix.other }}
+        git diff --exit-code || (echo '::error::Generated bindings are out-of-date. Make sure to update them by running `cargo run -p windows_bindings`'; exit 1)
+      shell: bash
