ci: Check generation of windows_api next to windows_bindings
And leaves room for windows_msvc and windows_gnu in the future.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -109,7 +109,7 @@ jobs:
     steps:
     - name: Checkout
       uses: actions/checkout@v2
-  
+
     - name: Run windows_fmt
       run: cargo run -p windows_fmt
 
@@ -117,16 +117,20 @@ jobs:
       shell: bash
       run: git diff --exit-code || (echo '::error::Some `build!` macros were improperly formatted. Please run `cargo run -p windows_fmt` and push again'; exit 1)
 
-  windows_bindings:
-    name: Check bindings
+  generation:
+    name: Check generation of `windows_${{ matrix.generator }}`
     runs-on: windows-latest
+    strategy:
+      matrix:
+        generator: [bindings, api]
+
     steps:
     - name: Checkout
       uses: actions/checkout@v2
 
-    - name: Run windows_bindings
-      run: cargo run -p windows_bindings
+    - name: Run windows_${{ matrix.generator }}
+      run: cargo run -p windows_${{ matrix.generator }}
 
     - name: Compare
       shell: bash
-      run: git diff --exit-code || (echo '::error::Generated bindings are out-of-date. Please run `cargo run -p windows_bindings`'; exit 1)
+      run: git diff --exit-code || (echo '::error::Generated `windows_${{ matrix.generator }}` are out-of-date. Please run `cargo run -p windows_${{ matrix.generator }}`'; exit 1)
