validate

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -66,7 +66,7 @@ jobs:
     steps:
     - uses: actions/checkout@v2
     - name: Run windows_fmt
-      run: cargo r -p windows_fmt
+      run: cargo run -p windows_fmt
     - name: Diff formatting result
       shell: bash
       run: git diff --exit-code || (echo '::error::Some `build!` macros were improperly formatted. Please run `cargo run -p windows_fmt` and push again'; exit 1)
@@ -77,7 +77,7 @@ jobs:
     steps:
     - uses: actions/checkout@v2
     - name: Run windows_bindings
-      run: |
-        cargo run -p windows_bindings
-        git diff --exit-code || (echo '::error::Generated bindings are out-of-date. Make sure to update them by running `cargo run -p windows_bindings`'; exit 1)
+      run: cargo run -p windows_bindings
+    - name: Diff formatting result
       shell: bash
+      run: git diff --exit-code || (echo '::error::Generated bindings are out-of-date. Please run `cargo run -p windows_bindings`'; exit 1)
