naming

diff --git a/.github/workflows/gen.yml b/.github/workflows/gen.yml
--- a/.github/workflows/gen.yml
+++ b/.github/workflows/gen.yml
@@ -11,16 +11,16 @@ env:
 
 jobs:
   generation:
-    name: Check generation of `tool_${{ matrix.generator }}`
+    name: tool_${{ matrix.tool }}
     runs-on: windows-latest
     strategy:
       matrix:
-        generator: [windows, sys, yml]
+        tool: [windows, sys, yml]
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-      - name: Run tool_${{ matrix.generator }}
-        run: cargo run -p tool_${{ matrix.generator }}
+      - name: Run
+        run: cargo run -p tool_${{ matrix.tool }}
       - name: Check
         shell: bash
-        run: git diff --exit-code || (echo '::error::Generated `tool_${{ matrix.generator }}` are out-of-date. Please run `cargo run -p tool_${{ matrix.generator }}`'; exit 1)
+        run: git diff --exit-code || (echo '::error::Generated `tool_${{ matrix.tool }}` is out-of-date. Please run `cargo run -p tool_${{ matrix.tool }}`'; exit 1)
